// <auto-generated />
using System;
using LouvorApp.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LouvorApp.api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260302232358_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("LouvorApp.Api.Models.Setlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Setlists");
                });

            modelBuilder.Entity("LouvorApp.Api.Models.SetlistSong", b =>
                {
                    b.Property<int>("SetlistId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SongId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TransposeShift")
                        .HasColumnType("INTEGER");

                    b.HasKey("SetlistId", "SongId");

                    b.HasIndex("SongId");

                    b.ToTable("SetlistSongs");
                });

            modelBuilder.Entity("LouvorApp.Api.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RawChordText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("LouvorApp.Api.Models.SetlistSong", b =>
                {
                    b.HasOne("LouvorApp.Api.Models.Setlist", "Setlist")
                        .WithMany("SetlistSongs")
                        .HasForeignKey("SetlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LouvorApp.Api.Models.Song", "Song")
                        .WithMany("SetlistSongs")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Setlist");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("LouvorApp.Api.Models.Setlist", b =>
                {
                    b.Navigation("SetlistSongs");
                });

            modelBuilder.Entity("LouvorApp.Api.Models.Song", b =>
                {
                    b.Navigation("SetlistSongs");
                });
#pragma warning restore 612, 618
        }
    }
}
